(function(){
  'use strict';
  const qs=window.NAHW_QUESTIONS;
  const $=id=>document.getElementById(id);
  const ar=n=>String(n).replace(/\d/g,d=>'٠١٢٣٤٥٦٧٨٩'[Number(d)]);
  const gates=qs.map((_,i)=>330+i*370);
  let index=0,score=0,attempts=0,missed=[],status='start',soundOn=true,audio=null,answered=false;
  const show=id=>$(id).classList.add('visible');
  const hide=id=>$(id).classList.remove('visible');
  const phaseName=i=>i<3?'المحطة الأولى':i<7?'المحطة الثانية':'المحطة الثالثة';
  function syncHud(){ $('stage').textContent=phaseName(Math.min(index,9));$('progress').textContent=`${ar(index)} / ١٠`;$('progress-fill').style.width=`${index*10}%`;$('score').textContent=ar(score);$('speed').textContent=ar(Math.round(window.Racer.road.speed));$('checkpoint-number').textContent=ar(index+1);}
  function tone(freq=500,len=.12,type='sine'){if(!soundOn)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.075,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+len);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+len+.01);}catch{}}
  function normalize(s){return s.normalize('NFKC').replace(/[\u064B-\u065F\u0670\u0640]/g,'').replace(/[،.؛:!؟?\u200c\u200d]/g,'').replace(/\s+/g,' ').trim();}
  function optionButton(label,value){const b=document.createElement('button');b.type='button';b.className='answer-btn';const badge=document.createElement('span');badge.className='answer-letter';badge.textContent=label;const text=document.createElement('span');text.textContent=value;if(label!==value)b.append(badge);b.append(text);b.addEventListener('click',()=>judge(label));return b;}
  function ask(){status='question';answered=false;attempts=0;const q=qs[index];window.Racer.pause();$('question-phase').textContent=q.stage;$('question-count').textContent=`البوابة ${ar(index+1)} من ١٠`;$('question-title').textContent=q.title;$('question-instruction').textContent=q.instruction||'';$('question-instruction').hidden=!q.instruction;$('question-prompt').textContent=q.prompt;$('answers').replaceChildren();$('feedback').hidden=true;$('continue-btn').hidden=true;$('reveal-btn').hidden=true;$('input-area').hidden=q.type!=='write';$('hint').hidden=!q.hint;$('hint').textContent=q.hint||'';$('written-answer').value='';if(q.type==='choice'){q.options.forEach(([letter,text])=>$('answers').append(optionButton(letter,text)));}else if(q.type==='classify'){['عاملة','غير عاملة'].forEach(x=>$('answers').append(optionButton(x,x)));}else{setTimeout(()=>$('written-answer').focus(),120);}show('question-screen');tone(440,.11);}
  function judge(value){if(status!=='question'||answered)return;const q=qs[index];const correct=q.type==='write'?normalize(value)===normalize(q.correct):value===q.correct;if(correct){answered=true;score+=attempts?5:10;syncHud();$('feedback').className='feedback correct';$('feedback').replaceChildren();const strong=document.createElement('strong');strong.textContent='إجابة صحيحة';const body=document.createElement('span');body.textContent=q.answer||q.correct;const explanation=document.createElement('small');explanation.textContent=q.explanation;$('feedback').append(strong,body,explanation);$('feedback').hidden=false;$('continue-btn').hidden=false;$('reveal-btn').hidden=true;[...$('answers').children].forEach(b=>b.disabled=true);tone(660,.1);setTimeout(()=>tone(880,.18),90);}else{attempts++;if(!missed.includes(index))missed.push(index);$('feedback').className='feedback incorrect';$('feedback').textContent='حاول مرة أخرى.';$('feedback').hidden=false;if(attempts>=2)$('reveal-btn').hidden=false;tone(215,.18,'triangle');}}
  function reveal(){if(status!=='question'||answered)return;const q=qs[index];answered=true;missed.includes(index)||missed.push(index);$('feedback').className='feedback shown';$('feedback').replaceChildren();const strong=document.createElement('strong');strong.textContent='الإجابة النموذجية';const body=document.createElement('span');body.textContent=q.answer||q.correct;const explanation=document.createElement('small');explanation.textContent=q.explanation;$('feedback').append(strong,body,explanation);$('feedback').hidden=false;$('continue-btn').hidden=false;$('reveal-btn').hidden=true;[...$('answers').children].forEach(b=>b.disabled=true);}
  function continueRace(){if(!answered)return;hide('question-screen');index++;syncHud();if(index>=qs.length){status='driving';window.Racer.resume();$('race-tip').textContent='خط النهاية أمامك!';}else{status='driving';window.Racer.resume();window.Racer.boost();$('race-tip').textContent='البوابة فُتحت — واصل السباق';}tone(750,.12);}
  function finish(){if(status==='finished')return;status='finished';window.Racer.pause();$('finish-summary').textContent=`جمعت ${ar(score)} من ١٠٠ نقطة، وفتحت ${ar(index)} بوابات.`;const review=$('review');review.replaceChildren();if(missed.length){const heading=document.createElement('h3');heading.textContent='مراجعة المحاولات';review.append(heading);missed.forEach(i=>{const q=qs[i],row=document.createElement('div');row.className='review-row';const p=document.createElement('strong');p.textContent=q.prompt;const a=document.createElement('span');a.textContent=q.answer||q.correct;row.append(p,a);review.append(row);});}else{const p=document.createElement('p');p.textContent='أجبت عن جميع البوابات من المحاولة الأولى.';review.append(p);}show('finish-screen');tone(880,.18);setTimeout(()=>tone(1040,.22),150);}
  function reset(){index=0;score=0;attempts=0;missed=[];answered=false;status='driving';window.Racer.reset();window.Racer.resume();hide('start-screen');hide('finish-screen');hide('question-screen');$('race-tip').textContent='قد سيارتك نحو البوابة التالية';syncHud();tone(550,.12);}
  window.NahwGame={nextGateDistance:()=>index<qs.length?gates[index]:Infinity,advance:(before,after)=>{if(status!=='driving')return;if(index<qs.length&&before<gates[index]&&after>=gates[index])ask();else if(index>=qs.length&&after>=gates.at(-1)+390)finish();},collision:()=>{if(status==='driving'){tone(135,.2,'sawtooth');$('race-tip').textContent='خفّفت المصادمة سرعتك — واصل القيادة';}}};
  $('start-btn').addEventListener('click',reset);$('restart-btn').addEventListener('click',reset);$('continue-btn').addEventListener('click',continueRace);$('reveal-btn').addEventListener('click',reveal);$('check-written').addEventListener('click',()=>judge($('written-answer').value));$('written-answer').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();judge(e.target.value);}});$('sound-toggle').addEventListener('click',e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♫':'♪';e.currentTarget.setAttribute('aria-label',soundOn?'إيقاف الصوت':'تشغيل الصوت');if(soundOn)tone();});
  const keymap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'accelerate',KeyW:'accelerate',ArrowDown:'brake',KeyS:'brake'};
  window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const key=keymap[e.code];if(key){e.preventDefault();window.Racer.input[key]=true;}});window.addEventListener('keyup',e=>{const key=keymap[e.code];if(key)window.Racer.input[key]=false;});window.addEventListener('blur',()=>Object.keys(window.Racer.input).forEach(k=>window.Racer.input[k]=false));
  document.querySelectorAll('.touch-controls button').forEach(button=>{const key=button.dataset.key;const down=e=>{e.preventDefault();button.setPointerCapture?.(e.pointerId);window.Racer.input[key]=true;button.classList.add('pressed');};const up=e=>{e.preventDefault();window.Racer.input[key]=false;button.classList.remove('pressed');};button.addEventListener('pointerdown',down);button.addEventListener('pointerup',up);button.addEventListener('pointercancel',up);button.addEventListener('lostpointercapture',up);});
  let last=0;function hudLoop(t){if(t-last>100){last=t;syncHud();const distance=window.NahwGame.nextGateDistance()-window.Racer.road.distance;$('checkpoint-sign').classList.toggle('near',status==='driving'&&distance<520&&distance>0);$('checkpoint-sign').setAttribute('aria-hidden',String(!(status==='driving'&&distance<520&&distance>0)));}requestAnimationFrame(hudLoop);}requestAnimationFrame(hudLoop);
  syncHud();
})();
